(function(global){
"use strict";
var CAT="__POS_CONFIG__", cache=[];
function marca(){return (global.BRAND&&BRAND.marca)||""}
function headers(){return{"Content-Type":"application/json","Prefer":"return=minimal","apikey":global.SUPABASE_KEY,"Authorization":"Bearer "+global.SUPABASE_KEY}}
function base(){return global.SUPABASE_URL+"/rest/v1/menu_items"}
function parse(row){try{var d=JSON.parse(row.descripcion||"{}");d._id=row.id;return d}catch(e){return null}}
function load(){return fetch(base()+"?marca=eq."+encodeURIComponent(marca())+"&categoria=eq."+encodeURIComponent(CAT)+"&select=*&order=orden,nombre",{headers:headers()}).then(function(r){if(!r.ok)throw Error();return r.json()}).then(function(rows){cache=rows.map(parse).filter(function(x){return x&&x.active!==false});global.POS_MENU_CONFIG=cache;render();return cache}).catch(function(){toast("No se pudo cargar la configuracion del menu");return[]})}
function save(type,data){data.type=type;data.active=true;var body={marca:marca(),categoria:CAT,nombre:type+":"+Date.now(),precio:0,descripcion:JSON.stringify(data),disponible:false,orden:Number(data.order)||0,estacion:"config"};return fetch(base(),{method:"POST",headers:headers(),body:JSON.stringify(body)}).then(function(r){if(!r.ok)throw Error();return load()})}
function archive(id){var item=cache.find(function(x){return x._id===id});if(!item)return;item.active=false;delete item._id;fetch(base()+"?id=eq."+encodeURIComponent(id)+"&marca=eq."+encodeURIComponent(marca())+"&categoria=eq."+encodeURIComponent(CAT),{method:"PATCH",headers:headers(),body:JSON.stringify({descripcion:JSON.stringify(item)})}).then(load)}
function esc2(s){return String(s||"").replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function categories(){var fromProducts=(global._prodCache||[]).filter(function(p){return p.categoria!==CAT}).map(function(p){return p.categoria});var configured=cache.filter(function(x){return x.type==="category"}).map(function(x){return x.name});return Array.from(new Set(fromProducts.concat(configured))).filter(Boolean).sort()}
function render(){var el=document.getElementById("menuConfigContent");if(!el)return;var cats=categories(),mods=cache.filter(function(x){return x.type==="modifier"}),comments=cache.filter(function(x){return x.type==="comment"});el.innerHTML='<section class="mc-section"><h3>Categorias</h3><div class="mc-add"><input id="mcCatName" placeholder="Nueva categoria"><button class="btn btn-primary" onclick="PosMenuConfig.addCategory()">Agregar</button></div>'+cats.map(function(c){return'<span class="mc-chip">'+esc2(c)+'</span>'}).join("")+'</section><section class="mc-section"><h3>Grupos de modificadores</h3><p>Una opcion por linea: Nombre | precio adicional</p><input id="mcModName" placeholder="Ej. Tipo de proteina"><input id="mcModCats" placeholder="Categorias separadas por coma; vacio = todas"><textarea id="mcModOptions" placeholder="Pollo | 0&#10;Camaron | 20&#10;Salmon | 30"></textarea><label class="chk"><input type="checkbox" id="mcModRequired"> Seleccion obligatoria</label><button class="btn btn-primary" onclick="PosMenuConfig.addModifier()">Crear grupo</button><div>'+mods.map(function(m){return'<div class="mc-row"><span><b>'+esc2(m.name)+'</b><small>'+esc2((m.options||[]).map(function(o){return o.name+(o.price?' +$'+o.price:'')}).join(', '))+'</small></span><button class="btn-sm danger" onclick="PosMenuConfig.archive(\''+m._id+'\')">Eliminar</button></div>'}).join("")+'</div></section><section class="mc-section"><h3>Comentarios fijos</h3><div class="mc-add"><input id="mcComment" placeholder="Ej. Sin cebolla"><input id="mcCommentCats" placeholder="Categorias; vacio = todas"><button class="btn btn-primary" onclick="PosMenuConfig.addComment()">Agregar</button></div>'+comments.map(function(c){return'<div class="mc-row"><span><b>'+esc2(c.text)+'</b><small>'+esc2((c.categories||[]).join(', ')||'Todos los platillos')+'</small></span><button class="btn-sm danger" onclick="PosMenuConfig.archive(\''+c._id+'\')">Eliminar</button></div>'}).join("")+'</section>';var dl=document.getElementById("pmCatList");if(dl)dl.innerHTML=cats.map(function(c){return'<option value="'+esc2(c)+'">'}).join("")}
function splitCats(v){return String(v||"").split(",").map(function(x){return x.trim()}).filter(Boolean)}
var api={load:load,open:function(){document.getElementById("menuConfigModal").classList.remove("hidden");load()},archive:archive,addCategory:function(){var n=document.getElementById("mcCatName").value.trim();if(!n)return toast("Escribe la categoria");save("category",{name:n,order:categories().length})},addModifier:function(){var n=document.getElementById("mcModName").value.trim(),lines=document.getElementById("mcModOptions").value.split(/\r?\n/).filter(Boolean),options=lines.map(function(line){var p=line.split("|");return{name:p[0].trim(),price:Number(p[1])||0}}).filter(function(x){return x.name});if(!n||!options.length)return toast("Escribe el grupo y sus opciones");save("modifier",{name:n,categories:splitCats(document.getElementById("mcModCats").value),required:document.getElementById("mcModRequired").checked,multiple:false,options:options})},addComment:function(){var t=document.getElementById("mcComment").value.trim();if(!t)return toast("Escribe el comentario");save("comment",{text:t,categories:splitCats(document.getElementById("mcCommentCats").value)})}};
global.PosMenuConfig=api;
})(window);
