(function(global){
"use strict";
var CAT="__POS_CONFIG__",cache=[];
function marca(){return(global.BRAND&&BRAND.marca)||""}
function headers(){return{"Content-Type":"application/json","Prefer":"return=minimal","apikey":global.SUPABASE_KEY,"Authorization":"Bearer "+global.SUPABASE_KEY}}
function base(){return global.SUPABASE_URL+"/rest/v1/menu_items"}
function parse(row){try{var d=JSON.parse(row.descripcion||"{}");d._id=row.id;return d}catch(e){return null}}
function load(){return fetch(base()+"?marca=eq."+encodeURIComponent(marca())+"&categoria=eq."+encodeURIComponent(CAT)+"&select=*&order=orden,nombre",{headers:headers()}).then(function(r){if(!r.ok)throw Error();return r.json()}).then(function(rows){cache=rows.map(parse).filter(function(x){return x&&x.active!==false});global.POS_MENU_CONFIG=cache;render();return cache}).catch(function(){toast("No se pudo cargar la configuracion del menu");return[]})}
function save(type,data){data.type=type;data.active=true;var body={categoria:CAT,nombre:type+":"+Date.now(),precio:0,descripcion:JSON.stringify(data),disponible:false,orden:Number(data.order)||0,estacion:"config"};return global.posMenu("create",{item:body}).then(load)}
function update(id,data){if(typeof data.active==="undefined")data.active=true;delete data._id;return global.posMenu("update",{id:id,changes:{descripcion:JSON.stringify(data)}}).then(load)}
function archive(id){var item=cache.find(function(x){return x._id===id});if(!item)return;item.active=false;update(id,item)}
function esc2(s){return String(s||"").replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function categories(){var fromProducts=(global._prodCache||[]).filter(function(p){return p.categoria!==CAT}).map(function(p){return p.categoria});var configured=cache.filter(function(x){return x.type==="category"}).map(function(x){return x.name});return Array.from(new Set(fromProducts.concat(configured))).filter(Boolean).sort()}
function defaultHours(){return{type:"business_hours",active:true,timezone:"America/Merida",days:{0:{enabled:true,open:"14:00",close:"22:30"},1:{enabled:true,open:"15:30",close:"22:50"},2:{enabled:true,open:"15:30",close:"22:50"},3:{enabled:true,open:"15:30",close:"22:50"},4:{enabled:true,open:"15:30",close:"22:50"},5:{enabled:true,open:"15:30",close:"22:50"},6:{enabled:true,open:"15:30",close:"22:50"}}}}
function hoursData(){return cache.find(function(x){return x.type==="business_hours"})||defaultHours()}
function hoursHtml(){var h=hoursData(),names=["Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado"];return '<section class="mc-section"><h3>Horario de pedidos en línea</h3><p>Fuera de este horario el cliente puede ver el menú, pero no puede enviar pedidos.</p>'+names.map(function(n,i){var d=h.days[i]||h.days[String(i)]||{};return '<div class="mc-hours-row"><label class="chk"><input type="checkbox" id="mcDay'+i+'" '+(d.enabled===false?'':'checked')+'> '+n+'</label><input type="time" id="mcOpen'+i+'" value="'+esc2(d.open||'15:30')+'"><span>a</span><input type="time" id="mcClose'+i+'" value="'+esc2(d.close||'22:50')+'"></div>'}).join('')+'<button class="btn btn-primary" onclick="PosMenuConfig.saveHours()">Guardar horario</button></section>'}
function render(){var el=document.getElementById("menuConfigContent");if(!el)return;var cats=categories(),mods=cache.filter(function(x){return x.type==="modifier"}),comments=cache.filter(function(x){return x.type==="comment"});el.innerHTML=hoursHtml()+'<section class="mc-section"><h3>Categorias</h3><div class="mc-add"><input id="mcCatName" placeholder="Nueva categoria"><button class="btn btn-primary" onclick="PosMenuConfig.addCategory()">Agregar</button></div>'+cats.map(function(c){return'<span class="mc-chip">'+esc2(c)+'</span>'}).join("")+'</section><section class="mc-section"><h3>Grupos de modificadores</h3><p>Una opcion por linea: Nombre | precio adicional</p><input id="mcModName" placeholder="Ej. Tipo de proteina"><input id="mcModCats" placeholder="Categorias separadas por coma; vacio = todas"><textarea id="mcModOptions" placeholder="Pollo | 0&#10;Camaron | 20&#10;Salmon | 30"></textarea><label class="chk"><input type="checkbox" id="mcModRequired"> Seleccion obligatoria</label><button class="btn btn-primary" onclick="PosMenuConfig.addModifier()">Crear grupo</button><div>'+mods.map(function(m){return'<div class="mc-row"><span><b>'+esc2(m.name)+'</b><small>'+esc2((m.options||[]).map(function(o){return o.name+(o.price?' +$'+o.price:'')}).join(', '))+'</small></span><button class="btn-sm danger" onclick="PosMenuConfig.archive(\''+m._id+'\')">Eliminar</button></div>'}).join("")+'</div></section><section class="mc-section"><h3>Comentarios fijos</h3><div class="mc-add"><input id="mcComment" placeholder="Ej. Sin cebolla"><input id="mcCommentCats" placeholder="Categorias; vacio = todas"><button class="btn btn-primary" onclick="PosMenuConfig.addComment()">Agregar</button></div>'+comments.map(function(c){return'<div class="mc-row"><span><b>'+esc2(c.text)+'</b><small>'+esc2((c.categories||[]).join(', ')||'Todos los platillos')+'</small></span><button class="btn-sm danger" onclick="PosMenuConfig.archive(\''+c._id+'\')">Eliminar</button></div>'}).join("")+'</section>';var dl=document.getElementById("pmCatList");if(dl)dl.innerHTML=cats.map(function(c){return'<option value="'+esc2(c)+'">'}).join("")}
function splitCats(v){return String(v||"").split(",").map(function(x){return x.trim()}).filter(Boolean)}
function saveHours(){var old=hoursData(),data=defaultHours();for(var i=0;i<7;i++)data.days[i]={enabled:document.getElementById("mcDay"+i).checked,open:document.getElementById("mcOpen"+i).value,close:document.getElementById("mcClose"+i).value};var action=old._id?update(old._id,data):save("business_hours",data);action.then(function(){toast("Horario guardado y sincronizado con pedidos en línea")})}
var api={load:load,open:function(){document.getElementById("menuConfigModal").classList.remove("hidden");load()},archive:archive,saveHours:saveHours,addCategory:function(){var n=document.getElementById("mcCatName").value.trim();if(!n)return toast("Escribe la categoria");save("category",{name:n,order:categories().length})},addModifier:function(){var n=document.getElementById("mcModName").value.trim(),lines=document.getElementById("mcModOptions").value.split(/\r?\n/).filter(Boolean),options=lines.map(function(line){var p=line.split("|");return{name:p[0].trim(),price:Number(p[1])||0}}).filter(function(x){return x.name});if(!n||!options.length)return toast("Escribe el grupo y sus opciones");save("modifier",{name:n,categories:splitCats(document.getElementById("mcModCats").value),required:document.getElementById("mcModRequired").checked,multiple:false,options:options})},addComment:function(){var t=document.getElementById("mcComment").value.trim();if(!t)return toast("Escribe el comentario");save("comment",{text:t,categories:splitCats(document.getElementById("mcCommentCats").value)})}};
global.PosMenuConfig=api;
})(window);
