(function(global){
"use strict";
var CATEGORY="__POS_PACKAGES__", editing=null, builder={fixed:[],groups:[]}, activeGroup=-1;
function el(id){return document.getElementById(id)}
function parseLines(text,withQty){return String(text||"").split(/\r?\n/).map(function(line){var p=line.split("|").map(function(x){return x.trim()});if(!p[0])return null;return withQty?{name:p[0],qty:Math.max(1,parseInt(p[1],10)||1),station:(p[2]||"cocina").toLowerCase()}:{name:p[0],station:(p[1]||"sushi").toLowerCase()}}).filter(Boolean)}
function lines(items,withQty){return(items||[]).map(function(x){return withQty?[x.name,x.qty||1,x.station||"cocina"].join(" | "):[x.name,x.station||"sushi"].join(" | ")}).join("\n")}
function parseRow(row){try{var x=JSON.parse(row.descripcion||"{}");x._configId=row.id;return x}catch(e){return null}}
function configs(rows){var out={};(rows||[]).filter(function(r){return r.categoria===CATEGORY&&r.disponible!==false}).forEach(function(r){var x=parseRow(r);if(x&&x.name)out[x.name]=x});return out}
function staticPackage(name){var found=null;(global.STATIC_MENU||[]).some(function(c){return(c.items||[]).some(function(i){if(i.name===name){found=i;return true}return false})});return found}
function legacyFixed(name){var n=String(name||"").toLowerCase(),s=String((global.BRAND||{}).marca||"").toLowerCase();if(s==="sakura"){if(n.indexOf("super paquete 4")===0)return[{name:"Oniguri de Philadelphia Empanizado (4 pzas)",qty:3,station:"sushi"},{name:"Papas a la Francesa",qty:1,station:"cocina"},{name:"Nestea",qty:2,station:"bebidas"}];if(n.indexOf("sakura lunch")===0)return[{name:"Medio Yakimeshi de Pollo",qty:1,station:"cocina"},{name:"Dedo de Queso Gouda",qty:1,station:"cocina"},{name:"Nestea",qty:1,station:"bebidas"}];if(n.indexOf("2 yakimeshi de pollo")===0)return[{name:"Yakimeshi de Pollo",qty:2,station:"cocina"}]}else{if(n.indexOf("paquete individual")===0)return[{name:"Papas a la Francesa",qty:1,station:"cocina"},{name:"Nestea",qty:1,station:"bebidas"}];if(n.indexOf("paquete pareja")===0)return[{name:"Yakimeshi de Pollo o Vegetariano",qty:2,station:"cocina"},{name:"Dedo de Queso Gouda",qty:2,station:"cocina"}];if(n.indexOf("paquete familiar")===0)return[{name:"Yakimeshi de Pollo",qty:2,station:"cocina"},{name:"Dedo de Queso Philadelphia",qty:3,station:"cocina"},{name:"Panchitos Jalapeños con Philadelphia",qty:1,station:"cocina"}]}return[]}
function normalProduct(p){return p&&p.disponible!==false&&p.categoria!==CATEGORY&&!/paquete|promo/i.test(p.categoria||"")}
function itemFromProduct(p,qty){return{name:p.nombre,qty:Math.max(1,qty||1),station:(p.estacion||"cocina").toLowerCase(),productId:p.id||null}}
function group(){return builder.groups[activeGroup]||null}
function renderSelected(kind){var box=el(kind==="fixed"?"pkgFixedBuilder":"pkgOptionsBuilder"),items=kind==="fixed"?builder.fixed:((group()||{}).options||[]);if(!box)return;box.innerHTML=items.length?items.map(function(x,i){return'<div class="pkg-selected-row"><span><b>'+esc(x.name)+'</b><small>'+esc(x.station||"sin estación")+'</small></span>'+(kind==="fixed"?'<span class="pkg-qty"><button type="button" onclick="PosPackageManager.qty(\''+kind+'\','+i+',-1)">−</button><b>'+x.qty+'</b><button type="button" onclick="PosPackageManager.qty(\''+kind+'\','+i+',1)">+</button></span>':'<span></span>')+'<button type="button" class="pkg-remove" title="Quitar" onclick="PosPackageManager.remove(\''+kind+'\','+i+')">×</button></div>'}).join(""):'<div class="pkg-empty">Todavía no agregas artículos</div>';el("pkgFixed").value=lines(builder.fixed,true);el("pkgOptions").value=lines(items,false)}
function renderProducts(){var q=String((el("pkgProductSearch")||{}).value||"").toLowerCase(),rows=(global._prodCache||[]).filter(normalProduct).filter(function(p){return!q||String(p.nombre||"").toLowerCase().indexOf(q)>=0||String(p.categoria||"").toLowerCase().indexOf(q)>=0}).slice(0,80),box=el("pkgProductCatalog");if(!box)return;box.innerHTML=rows.length?rows.map(function(p){return'<div class="pkg-catalog-item"><span><b>'+esc(p.nombre)+'</b><small>'+esc(p.categoria||"")+' · '+esc(p.estacion||"sin estación")+'</small></span><span class="pkg-catalog-actions"><button type="button" class="pkg-add-fixed" title="Agregar como incluido fijo" onclick="PosPackageManager.add(\'fixed\',\''+p.id+'\')">+ Fijo</button><button type="button" class="pkg-add-option" title="Agregar como opción para elegir" onclick="PosPackageManager.add(\'options\',\''+p.id+'\')">+ Opción</button></span></div>'}).join(""):'<div class="pkg-empty">No se encontraron artículos</div>'}
function add(kind,id){var p=(global._prodCache||[]).find(function(x){return String(x.id)===String(id)});if(!normalProduct(p))return;if(kind==="options"&&!group()){toast("Primero crea o selecciona un grupo");return}var list=kind==="fixed"?builder.fixed:group().options,existing=list.find(function(x){return x.name===p.nombre});if(existing&&kind==="fixed")existing.qty+=1;else if(!existing)list.push(itemFromProduct(p,1));renderSelected(kind);renderGroups()}
function qty(kind,index,delta){var list=kind==="fixed"?builder.fixed:((group()||{}).options||[]),x=list[index];if(!x)return;x.qty=Math.max(1,(x.qty||1)+delta);renderSelected(kind)}
function remove(kind,index){var list=kind==="fixed"?builder.fixed:((group()||{}).options||[]);list.splice(index,1);renderSelected(kind);renderGroups()}
function addGroup(){builder.groups.push({name:"Nuevo grupo",choose:1,repeat:true,options:[]});activeGroup=builder.groups.length-1;renderGroups();renderSelected("options")}
function selectGroup(i){activeGroup=i;renderGroups();renderSelected("options")}
function updateGroup(i,key,value){var g=builder.groups[i];if(!g)return;g[key]=key==="choose"?Math.max(1,parseInt(value,10)||1):value;renderGroups(false);if(i===activeGroup&&el("pkgActiveGroupTitle"))el("pkgActiveGroupTitle").textContent="Opciones: "+g.name}
function removeGroup(i){builder.groups.splice(i,1);activeGroup=builder.groups.length?Math.min(i,builder.groups.length-1):-1;renderGroups();renderSelected("options")}
function renderGroups(){var box=el("pkgGroupsBuilder");if(!box)return;box.innerHTML=builder.groups.length?builder.groups.map(function(g,i){return'<div class="pkg-group-card'+(i===activeGroup?' active':'')+'" onclick="PosPackageManager.selectGroup('+i+')"><div class="pkg-group-head"><input value="'+esc(g.name)+'" onclick="event.stopPropagation()" onchange="PosPackageManager.updateGroup('+i+',\'name\',this.value)" placeholder="Nombre del grupo"><button type="button" class="pkg-remove" onclick="event.stopPropagation();PosPackageManager.removeGroup('+i+')">×</button></div><div class="pkg-group-meta"><label>Debe escoger<input type="number" min="1" value="'+g.choose+'" onclick="event.stopPropagation()" onchange="PosPackageManager.updateGroup('+i+',\'choose\',this.value)"></label><label>Opciones disponibles<input value="'+g.options.length+'" disabled></label></div><label class="pkg-group-repeat" onclick="event.stopPropagation()"><input type="checkbox" '+(g.repeat?'checked':'')+' onchange="PosPackageManager.updateGroup('+i+',\'repeat\',this.checked)"> Permitir repetir</label></div>'}).join(''):'<div class="pkg-empty">Crea un grupo para comenzar</div>';var active=el("pkgActiveGroup");if(active)active.classList.toggle("hidden",!group());if(group()&&el("pkgActiveGroupTitle"))el("pkgActiveGroupTitle").textContent="Opciones: "+group().name}
function articleType(value){if(value!=="package")return;var name=(el("pmName")||{}).value||"",price=(el("pmPrice")||{}).value||"",desc=(el("pmDesc")||{}).value||"";open("");el("pkgName").value=name;el("pkgPrice").value=price;el("pkgDesc").value=desc;el("pmType").value="normal"}
function open(name){var cfg=(global.POS_PACKAGES_BY_NAME||{})[name]||null,prod=(global._prodCache||[]).find(function(p){return p.nombre===name}),old=staticPackage(name)||{},pkg=old.package||{};if(!cfg&&name)cfg={name:name,price:prod&&prod.precio,description:(prod&&prod.descripcion)||old.desc||"",choose:pkg.count||0,repeat:pkg.repeat!==false,options:(pkg.options||pkg.rolls||[]).map(function(x){return typeof x==="string"?{name:x,station:"sushi"}:x}),fixed:pkg.fixed||legacyFixed(name)};editing={productId:prod&&prod.id,configId:cfg&&cfg._configId,name:name};var legacy=(cfg&&cfg.options&&cfg.options.length)?[{name:"Opciones",choose:cfg.choose||1,repeat:cfg.repeat!==false,options:cfg.options}]:[];builder={fixed:(cfg&&cfg.fixed||[]).map(function(x){return{name:x.name,qty:x.qty||1,station:x.station||"cocina",productId:x.productId||null}}),groups:(cfg&&cfg.groups||legacy).map(function(g){return{name:g.name||"Opciones",choose:g.choose||1,repeat:g.repeat!==false,options:(g.options||[]).map(function(x){return typeof x==="string"?{name:x,qty:1,station:"sushi"}:x})}})};activeGroup=builder.groups.length?0:-1;el("pkgName").value=(cfg&&cfg.name)||(prod&&prod.nombre)||"";el("pkgPrice").value=(cfg&&cfg.price)||(prod&&prod.precio)||"";el("pkgDesc").value=(cfg&&cfg.description)||(prod&&prod.descripcion)||"";if(el("deletePackageBtn"))el("deletePackageBtn").classList.toggle("hidden",!(editing.productId||editing.configId));if(el("pkgProductSearch"))el("pkgProductSearch").value="";renderProducts();renderSelected("fixed");renderGroups();renderSelected("options");el("packageModal").classList.remove("hidden")}
function request(method,url,data){return fetch(url,{method:method,headers:{"Content-Type":"application/json","Prefer":"return=minimal","apikey":SUPABASE_KEY,"Authorization":"Bearer "+SUPABASE_KEY},body:JSON.stringify(data)}).then(function(r){if(!r.ok)throw new Error("HTTP "+r.status)})}
function save(){var name=el("pkgName").value.trim(),price=Number(el("pkgPrice").value),fixed=builder.fixed.slice(),groups=builder.groups.slice(),description=el("pkgDesc").value.trim();if(!name||!Number.isFinite(price)||price<0){toast("Completa nombre y precio");return}if(!fixed.length&&!groups.length){toast("Agrega productos fijos o grupos de selección");return}for(var gi=0;gi<groups.length;gi++){var g=groups[gi];if(!g.name.trim()||!g.options.length){toast("Completa el nombre y las opciones de cada grupo");return}if(!g.repeat&&g.choose>g.options.length){toast("En "+g.name+" la cantidad supera las opciones disponibles");return}}var allOptions=[];groups.forEach(function(g){g.options.forEach(function(x){if(!allOptions.some(function(y){return y.name===x.name}))allOptions.push(x)})});var first=groups[0]||{choose:0,repeat:true,options:[]},marca=BRAND.marca||"",base=API.replace("/rest/v1/orders","/rest/v1/menu_items"),cfg={version:3,name:name,price:price,description:description,groups:groups,choose:first.choose,repeat:first.repeat,options:allOptions,fixed:fixed},product={categoria:"Paquetes y Promos",nombre:name,precio:price,descripcion:description,estacion:"paquete",marca:marca,disponible:true},config={categoria:CATEGORY,nombre:name,precio:0,descripcion:JSON.stringify(cfg),estacion:"sistema",marca:marca,disponible:true};var purl=editing&&editing.productId?base+"?id=eq."+encodeURIComponent(editing.productId)+"&marca=eq."+encodeURIComponent(marca):base,curl=editing&&editing.configId?base+"?id=eq."+encodeURIComponent(editing.configId)+"&marca=eq."+encodeURIComponent(marca):base;el("savePackageBtn").disabled=true;Promise.all([request(editing&&editing.productId?"PATCH":"POST",purl,product),request(editing&&editing.configId?"PATCH":"POST",curl,config)]).then(function(){el("packageModal").classList.add("hidden");toast("Paquete guardado y disponible");fetchProducts()}).catch(function(){toast("No se pudo guardar el paquete")}).finally(function(){el("savePackageBtn").disabled=false})}
function removePackage(){if(!editing||(!editing.productId&&!editing.configId))return;var name=el("pkgName").value.trim()||editing.name||"este paquete";if(!confirm("¿Eliminar definitivamente el paquete “"+name+"”?\n\nLos pedidos anteriores conservarán su información."))return;var marca=BRAND.marca||"",base=API.replace("/rest/v1/orders","/rest/v1/menu_items"),jobs=[];if(editing.productId)jobs.push(request("DELETE",base+"?id=eq."+encodeURIComponent(editing.productId)+"&marca=eq."+encodeURIComponent(marca),{}));if(editing.configId)jobs.push(request("DELETE",base+"?id=eq."+encodeURIComponent(editing.configId)+"&marca=eq."+encodeURIComponent(marca),{}));el("deletePackageBtn").disabled=true;Promise.all(jobs).then(function(){el("packageModal").classList.add("hidden");toast("Paquete eliminado");fetchProducts()}).catch(function(){toast("No se pudo eliminar el paquete")}).finally(function(){el("deletePackageBtn").disabled=false})}
function install(){if(typeof global.apiGet!=="function")return;var original=global.apiGet;global.apiGet=function(path){return original(path).then(function(rows){if(String(path).indexOf("menu_items?")!==0)return rows;global.POS_PACKAGES_BY_NAME=configs(rows);var cat=(global.STATIC_MENU||[]).find(function(c){return c.name==="Paquetes y Promos"});if(!cat){cat={name:"Paquetes y Promos",items:[]};(global.STATIC_MENU||[]).push(cat)}Object.keys(global.POS_PACKAGES_BY_NAME).forEach(function(name){var c=global.POS_PACKAGES_BY_NAME[name],it=(cat.items||[]).find(function(x){return x.name===name});if(!it){it={name:name};cat.items.push(it)}it.price=c.price;it.desc=c.description||"";it.package={count:c.choose||0,rolls:c.options||[],options:c.options||[],fixed:c.fixed||[],repeat:c.repeat!==false,groups:c.groups||[]}});return rows.filter(function(r){return r.categoria!==CATEGORY})})}}
global.PosPackageManager={category:CATEGORY,configs:configs,open:open,save:save,removePackage:removePackage,articleType:articleType,renderProducts:renderProducts,add:add,qty:qty,remove:remove,addGroup:addGroup,selectGroup:selectGroup,updateGroup:updateGroup,removeGroup:removeGroup};install();
var legacyEdit=global.PosEditProd;
global.PosEditProd=function(pid){var p=(global._prodCache||[]).find(function(r){return r.id===pid});if(!p){toast("No se encontró el producto");return}if(/paquete|promo/i.test(p.categoria||""))return open(p.nombre);if(typeof legacyEdit==="function")legacyEdit(pid);else{el("pmCat").value=p.categoria||"";el("pmName").value=p.nombre||"";el("pmPrice").value=p.precio||0;el("pmDesc").value=p.descripcion||"";el("pmEstacion").value=p.estacion||"";el("addProductBtn").textContent="Guardar cambios";el("addProductBtn").dataset.editId=pid}var modal=el("productsModal"),body=modal&&modal.querySelector(".modal-body");if(body)body.scrollTop=0;setTimeout(function(){el("pmName")&&el("pmName").focus()},50);toast("Editando: "+p.nombre+". Guarda los cambios arriba.")};
})(window);
